spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    show-sql: true

  mail:
    host: ${SMTP_HOST} # smtp.gmail.com
    port: ${SMTP_PORT} # Standard port for TLS/secure email
    username: ${SMTP_USERNAME} # Gmail address
    password: ${SMTP_PASSWORD} # App Password (No spaces!)
    non-reply-email: wesamalsaleh23@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#          ssl:
#            enable: true

  jwt:
    secret-key: ${JWT_SECRET}
    access-token-validity-seconds: 604800 # 604800 is 7 days in seconds
    refresh-token-validity-seconds: 604800 # 604800 is 7 days in seconds

app:
  base-url: "http://localhost:8080"